config/routes.rb
Rails.application.routes.draw do
  # Page Routes
  get '/' => 'pages#index'
  # get '/help' => 'pages#help'
  # get '/test' => 'pages#test'
  get '/error' => 'pages#error'
  get '/requested/:id' => 'pages#requested'

  # API Routes
  get '/api/hack/count' => 'api#get_hack_count'
  get '/api/hack/:id/data' => 'api#get_hack_data'
  get '/api/hack/:id/versions' => 'api#get_hack_version_count'
  get '/api/hack/:id/version/:vid' => 'api#get_hack_version_data'

  # Hack Routes
  resources :hacks
  get '/all' => 'hacks#all'
  get '/random' => 'hacks#random'

  get '/hack/:id' => 'hacks#view'
  get '/hack/edit/:id' => 'hacks#edit'
  post '/hack/save/:id' => 'hacks#save'
  get '/hack/delete/:id' => 'hacks#delete'
  post '/hack/confirmdelete/:id' => 'hacks#confirm_delete'

  get '/hack/report/:id' => 'hacks#add_report'
  post '/hack/report/:id' => 'hacks#create_report'

  get '/hack/version/add/:id' => 'hacks#add_version'
  post '/hack/version/create/:id' => 'hacks#create_version'
  get '/hack/version/edit/:id' => 'hacks#edit_version'
  post '/hack/version/save/:id' => 'hacks#save_version'
  get '/hack/version/delete/:id' => 'hacks#delete_version'
  post '/hack/version/confirmdelete/:id' => 'hacks#confirm_delete_version'

  # Search Routes
  get '/search' => 'search#index'

  # Admin Routes
  get '/admin' => 'admin#index'
  get '/admin/user/list' => 'admin#list_users'
  get '/admin/user/password/:id' => 'admin#change_user_password'
  post '/admin/user/password/:id' => 'admin#save_change_user_password'
  get '/admin/user/delete/:id' => 'admin#delete_user'
  post '/admin/user/delete/:id' => 'admin#confirm_delete_user'
  get '/admin/user/grant/:id' => 'admin#grant_admin'
  post '/admin/user/grant/:id' => 'admin#confirm_grant_admin'
  get '/admin/user/revoke/:id' => 'admin#revoke_admin'
  post '/admin/user/revoke/:id' => 'admin#confirm_revoke_admin'
  get '/admin/reports/list' => 'admin#list_user_reports'
  get '/admin/reports/delete/:id' => 'admin#delete_user_report'
  post '/admin/reports/delete/:id' => 'admin#confirm_delete_user_report'
  get '/admin/reports/ban/:id' => 'admin#ban_reporter'
  post '/admin/reports/ban/:id' => 'admin#confirm_ban_reporter'
  get '/admin/reports/:id/ipaddress' => 'admin#request_report_ip_address'
  post '/admin/reports/:id/ipaddress' => 'admin#submit_request_report_ip_address'
  get '/admin/hack/add' => 'hacks#add'
  post '/admin/hack/add' => 'hacks#create'
  get '/admin/test' => 'admin#test'

  # Authentication Routes
  resources :users
  get '/signup'  => 'users#new'
  get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HacksDB - <%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  </head>

  <body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">HacksDB</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/all">All Hacks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/random">Random Hack</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="/search">Search Hacks</a>
          </li> -->
          <!-- <li class="nav-item">
            <a class="nav-link" href="/help">Help</a>
          </li> -->
          <% if current_user %>
            <% if current_user.admin %>
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Area</a>
              </li>
            <% end %>
          <% end %>
        </ul>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "Log out", logout_path, method: "delete", class: 'nav-link' %>
            </li>
          </ul>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", '/login', class: 'nav-link' %>
          </li> 
          <li class="nav-item">
            <%= link_to "Signup", '/signup', class: 'nav-link' %>
          </li> 
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <p class="text-center" style="font-style: italics;">Coded with ❤️ by <a href="https://gitlab.com/nsuchy">Nathaniel Suchy</a></p>
  </body>
</html>